import Foundation

enum QuestionType: String, Codable, Hashable {
    case choice
    case typed
}

enum ExplanationLanguage: String, Codable, CaseIterable, Identifiable {
    case english
    case danish

    var id: String { rawValue }
    var label: String { self == .english ? "English" : "Dansk" }
    var short: String { self == .english ? "EN" : "DA" }
}

struct Explanation: Codable, Hashable {
    let en: String
    let da: String

    func text(in language: ExplanationLanguage) -> String {
        language == .danish ? da : en
    }
}

/// One quiz item. Loaded from `Content/<topic>.json` or generated by `VerbDrill`.
struct Question: Codable, Identifiable, Hashable {
    let id: String
    let topic: String
    let level: Int
    let type: QuestionType
    let prompt: String
    let hint: String?
    let options: [String]?
    let answer: String
    let accepted: [String]?
    let explanation: Explanation
    let tags: [String]

    static let blankMarker = "___"

    var allAccepted: [String] { [answer] + (accepted ?? []) }

    /// Text before and after the blank.
    var promptParts: (before: String, after: String) {
        guard let range = prompt.range(of: Question.blankMarker) else { return (prompt, "") }
        return (String(prompt[..<range.lowerBound]), String(prompt[range.upperBound...]))
    }

    /// The sentence with the correct answer filled in.
    var filledPrompt: String {
        prompt.replacingOccurrences(of: Question.blankMarker, with: answer)
    }

    var isGenerated: Bool { id.hasPrefix("verbdrill-") }
}

struct TopicFile: Codable {
    let topic: String
    let questions: [Question]
}

struct Verb: Codable, Hashable, Identifiable {
    let infinitive: String
    let present: String
    let past: String
    let auxiliary: String
    let participle: String
    let group: String

    var id: String { infinitive }
    var isIrregular: Bool { group.hasPrefix("uregel") }
    /// "har/er" verbs accept either auxiliary.
    var auxiliaries: [String] { auxiliary.split(separator: "/").map(String.init) }
    var perfect: String { "\(auxiliaries[0]) \(participle)" }
}

struct VerbFile: Codable {
    let verbs: [Verb]
}
